[".config/ghostty/themes/dracula"]
type = "file"
url = "https://raw.githubusercontent.com/dracula/ghostty/main/dracula"

[".oh-my-zsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"