{{- if eq .chezmoi.os "darwin" }}
[".config/ghostty/themes/dracula"]
type = "file"
url = "https://raw.githubusercontent.com/dracula/ghostty/main/dracula"
{{- end }}

[".oh-my-zsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact = true
exclude = ['*/plugins/chezmoi']
stripComponents = 1
refreshPeriod = "168h"

[".oh-my-zsh/plugins/chezmoi"]
type = "archive"
url = "https://github.com/mass8326/zsh-chezmoi/archive/main.tar.gz"
exact = true
stripComponents = 1